//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelPaint.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixelPaint.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schwarz ähnelt.
        /// </summary>
        internal static string DE_BLACK {
            get {
                return ResourceManager.GetString("DE_BLACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blau ähnelt.
        /// </summary>
        internal static string DE_BLUE {
            get {
                return ResourceManager.GetString("DE_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        internal static string DE_EDIT {
            get {
                return ResourceManager.GetString("DE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportieren ähnelt.
        /// </summary>
        internal static string DE_EXPORT {
            get {
                return ResourceManager.GetString("DE_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        internal static string DE_FILE {
            get {
                return ResourceManager.GetString("DE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grün ähnelt.
        /// </summary>
        internal static string DE_GREEN {
            get {
                return ResourceManager.GetString("DE_GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu ähnelt.
        /// </summary>
        internal static string DE_NEW {
            get {
                return ResourceManager.GetString("DE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnen ähnelt.
        /// </summary>
        internal static string DE_OPEN {
            get {
                return ResourceManager.GetString("DE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die andere ähnelt.
        /// </summary>
        internal static string DE_OTHERS {
            get {
                return ResourceManager.GetString("DE_OTHERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pixel: ähnelt.
        /// </summary>
        internal static string DE_PIXELS {
            get {
                return ResourceManager.GetString("DE_PIXELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pixel Grösse... ähnelt.
        /// </summary>
        internal static string DE_PIXELSIZE {
            get {
                return ResourceManager.GetString("DE_PIXELSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rot ähnelt.
        /// </summary>
        internal static string DE_RED {
            get {
                return ResourceManager.GetString("DE_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wiederholen ähnelt.
        /// </summary>
        internal static string DE_REDO {
            get {
                return ResourceManager.GetString("DE_REDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string DE_RESET {
            get {
                return ResourceManager.GetString("DE_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        internal static string DE_SAVE {
            get {
                return ResourceManager.GetString("DE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern unter... ähnelt.
        /// </summary>
        internal static string DE_SAVEAS {
            get {
                return ResourceManager.GetString("DE_SAVEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rückgängig ähnelt.
        /// </summary>
        internal static string DE_UNDO {
            get {
                return ResourceManager.GetString("DE_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbennant ähnelt.
        /// </summary>
        internal static string DE_UNNAMED {
            get {
                return ResourceManager.GetString("DE_UNNAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiss ähnelt.
        /// </summary>
        internal static string DE_WHITE {
            get {
                return ResourceManager.GetString("DE_WHITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gelb ähnelt.
        /// </summary>
        internal static string DE_YELLOW {
            get {
                return ResourceManager.GetString("DE_YELLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Black ähnelt.
        /// </summary>
        internal static string EN_BLACK {
            get {
                return ResourceManager.GetString("EN_BLACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blue ähnelt.
        /// </summary>
        internal static string EN_BLUE {
            get {
                return ResourceManager.GetString("EN_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string EN_EDIT {
            get {
                return ResourceManager.GetString("EN_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        internal static string EN_EXPORT {
            get {
                return ResourceManager.GetString("EN_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string EN_FILE {
            get {
                return ResourceManager.GetString("EN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Green ähnelt.
        /// </summary>
        internal static string EN_GREEN {
            get {
                return ResourceManager.GetString("EN_GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        internal static string EN_NEW {
            get {
                return ResourceManager.GetString("EN_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        internal static string EN_OPEN {
            get {
                return ResourceManager.GetString("EN_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die others ähnelt.
        /// </summary>
        internal static string EN_OTHERS {
            get {
                return ResourceManager.GetString("EN_OTHERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pixels: ähnelt.
        /// </summary>
        internal static string EN_PIXELS {
            get {
                return ResourceManager.GetString("EN_PIXELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pixel Size... ähnelt.
        /// </summary>
        internal static string EN_PIXELSIZE {
            get {
                return ResourceManager.GetString("EN_PIXELSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red ähnelt.
        /// </summary>
        internal static string EN_RED {
            get {
                return ResourceManager.GetString("EN_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redo ähnelt.
        /// </summary>
        internal static string EN_REDO {
            get {
                return ResourceManager.GetString("EN_REDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string EN_RESET {
            get {
                return ResourceManager.GetString("EN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string EN_SAVE {
            get {
                return ResourceManager.GetString("EN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as... ähnelt.
        /// </summary>
        internal static string EN_SAVEAS {
            get {
                return ResourceManager.GetString("EN_SAVEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo ähnelt.
        /// </summary>
        internal static string EN_UNDO {
            get {
                return ResourceManager.GetString("EN_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unnamed* ähnelt.
        /// </summary>
        internal static string EN_UNNAMED {
            get {
                return ResourceManager.GetString("EN_UNNAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die White ähnelt.
        /// </summary>
        internal static string EN_WHITE {
            get {
                return ResourceManager.GetString("EN_WHITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yellow ähnelt.
        /// </summary>
        internal static string EN_YELLOW {
            get {
                return ResourceManager.GetString("EN_YELLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Noir ähnelt.
        /// </summary>
        internal static string FR_BLACK {
            get {
                return ResourceManager.GetString("FR_BLACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bleu ähnelt.
        /// </summary>
        internal static string FR_BLUE {
            get {
                return ResourceManager.GetString("FR_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edition ähnelt.
        /// </summary>
        internal static string FR_EDIT {
            get {
                return ResourceManager.GetString("FR_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exporter ähnelt.
        /// </summary>
        internal static string FR_EXPORT {
            get {
                return ResourceManager.GetString("FR_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fichier ähnelt.
        /// </summary>
        internal static string FR_FILE {
            get {
                return ResourceManager.GetString("FR_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vert ähnelt.
        /// </summary>
        internal static string FR_GREEN {
            get {
                return ResourceManager.GetString("FR_GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nouveau ähnelt.
        /// </summary>
        internal static string FR_NEW {
            get {
                return ResourceManager.GetString("FR_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ouvrir ähnelt.
        /// </summary>
        internal static string FR_OPEN {
            get {
                return ResourceManager.GetString("FR_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autres ähnelt.
        /// </summary>
        internal static string FR_OTHERS {
            get {
                return ResourceManager.GetString("FR_OTHERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pixels ähnelt.
        /// </summary>
        internal static string FR_PIXELS {
            get {
                return ResourceManager.GetString("FR_PIXELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taille de pixel ähnelt.
        /// </summary>
        internal static string FR_PIXELSIZE {
            get {
                return ResourceManager.GetString("FR_PIXELSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rouge ähnelt.
        /// </summary>
        internal static string FR_RED {
            get {
                return ResourceManager.GetString("FR_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refaire ähnelt.
        /// </summary>
        internal static string FR_REDO {
            get {
                return ResourceManager.GetString("FR_REDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Réinitialiser ähnelt.
        /// </summary>
        internal static string FR_RESET {
            get {
                return ResourceManager.GetString("FR_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enregistrer ähnelt.
        /// </summary>
        internal static string FR_SAVE {
            get {
                return ResourceManager.GetString("FR_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enregistrer sous ähnelt.
        /// </summary>
        internal static string FR_SAVEAS {
            get {
                return ResourceManager.GetString("FR_SAVEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annuler ähnelt.
        /// </summary>
        internal static string FR_UNDO {
            get {
                return ResourceManager.GetString("FR_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anonyme* ähnelt.
        /// </summary>
        internal static string FR_UNNAMED {
            get {
                return ResourceManager.GetString("FR_UNNAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blanc ähnelt.
        /// </summary>
        internal static string FR_WHITE {
            get {
                return ResourceManager.GetString("FR_WHITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jaune ähnelt.
        /// </summary>
        internal static string FR_YELLOW {
            get {
                return ResourceManager.GetString("FR_YELLOW", resourceCulture);
            }
        }
    }
}
